CREATE TABLE Animal
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    age         INTEGER                                  NOT NULL,
    foodHabits  INTEGER,
    dateArrival date,
    CONSTRAINT pk_animal PRIMARY KEY (id)
);